main:
	g++ -O3 -std=c++20 \
    	-I"/opt/homebrew/include/eigen3" \
    	-I"../include/" \
    	main.cpp \
    	-o main.out
main_debug:
	g++ -O3 -std=c++20 -DDEBUG \
    	-I"/opt/homebrew/include/eigen3" \
    	-I"../include/" \
    	main.cpp \
    	-o main.out